modLoader="javafml" 
loaderVersion="[46,)" 
license="All rights reserved"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"
[[mods]] 
modId="projectrpg" 
version="${file.jarVersion}" 
displayName="Project RPG"
#updateJSONURL="https://change.me.example.invalid/updates.json" 
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" 
#logoFile="projectrpg.png" 
credits="The Community and Contributors of the Project" 
authors="Project RPG Team and Contributors" 
#displayTest="MATCH_VERSION" 
description='''
Project RPG is a hub mod for adding RPG elements to your Minecraft world.
The mod comes with some default features but is designed to be expanded by
addons that you choose to shape your RPG experience.
'''

[[dependencies.projectrpg]]
    modId="forge" 
    mandatory=true 
    versionRange="[46,)" 
    ordering="NONE"
    side="BOTH"
	
[[dependencies.projectrpg]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
