modLoader="javafml" 
loaderVersion="[45,)" 
license="All rights reserved"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"
[[mods]] 
modId="${modid}" 
version="${file.jarVersion}" 
displayName="Example Mod" #
#updateJSONURL="https://change.me.example.invalid/updates.json" 
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" 
#logoFile="${modid}.png" 
credits="Thanks for this example mod goes to Java" 
authors="Love, Cheese and small house plants" 
#displayTest="MATCH_VERSION" 
description='''
This is a long form description of the mod. You can write whatever you want here

Have some lorem ipsum.
'''

[[dependencies.${modid}]]
    modId="forge" 
    mandatory=true 
    versionRange="[45,)" 
    ordering="NONE"
    side="BOTH"
	
[[dependencies.${modid}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
